version: '3.1'
services:
  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 1234:8080
    links:
      - postgres
